--Check LIST INDEX PARTITION
select INDEX_OWNER, partition_name, partition_position, status 
from dba_ind_partitions 
where index_name='USER_MSG_LOCAL_IDX';


--SCRIPT COLLECT
SELECT 'ALTER INDEX '||OWNER||'.'||INDEX_NAME||' REBUILD PARTITION ONLINE;' 
FROM DBA_INDEXES 
WHERE TABLE_NAME='TCNPM608T';


--------------------------------------------------------------------------------------------------------------------------------------------
1. partition online
ALTER INDEX DGPOS.ARP_REQUEST_DETAIL_MSISDN REBUILD PARTITION ONLINE; --tanpa parallel

ALTER INDEX DGPOS.USER_MSG_LOCAL_IDX PARTITION SYS_DEFAULT REBUILD ONLINE PARALLEL 4;
ALTER INDEX DGPOS.USER_MSG_LOCAL_IDX PARTITION SYS_DEFAULT NOPARALLEL;
ALTER INDEX DGPOS.USER_MSG_LOCAL_IDX REBUILD PARTITION USER_MESSAGES_JAN2021 ONLINE PARALLEL 4;
ALTER INDEX DGPOS.USER_MSG_LOCAL_IDX REBUILD PARTITION USER_MESSAGES_JAN2021 NOPARALLEL;
dst..


2. rebuild online
ALTER INDEX TSEL_OIM.SYS_IL0000222362C00003$$ REBUILD ONLINE TABLESPACE NEWTABLESPACE;


3. rebuild with parallel
ALTER INDEX DGPOS.DO_DETAIL_KEY_MSISDN_SN_INDEX REBUILD  ONLINE PARALLEL 8 TABLESPACE TBS_DELIVERY_ORDER_DETAIL;


--------------------------------------------------------------------------------------------------------------------------------------------

--ALTER TRXID PARTITION TABLE AND INDEX:

ALTER TABLE NBPUSER.TRXID_NEW MOVE PARTITION P_NODE1 INITRANS 10 STORAGE (FREELISTS 16 FREELIST GROUPS 2);
ALTER INDEX NBPUSER.TRXID_COMPOSITEINDEX_NEW REBUILD PARTITION P_NODE1 INITRANS 10 STORAGE (FREELIST GROUPS 2 FREELISTS 16);
ALTER INDEX NBPUSER.TRXID_PRIMARY_KEY_NEW REBUILD INITRANS 10 STORAGE (FREELIST GROUPS 2 FREELISTS 16);


--------------------------------------------------------------------------------------------------------------------------------------------

--MOVE TABLE PARTITION AND REBUILD INDEX

ALTER TABLE CAMPAIGN_TRACKING.CMS_TRACKINGSTREAM MOVE PARTITION SYS_P2434882 TABLESPACE TRACKINGSTREAM_092018 PARALLEL(DEGREE 4);
ALTER INDEX CMS_TRACKINGSTREAM_IDX01 REBUILD PARTITION SYS_P2434882 TABLESPACE TRACKINGSTREAM_IDX_092018 NOLOGGING PARALLEL(DEGREE 4);


ALTER INDEX DGPOS.SYS_C0010202 REBUILD ONLINE PARALLEL 8 NOLOGGING;
ALTER INDEX DGPOS.SYS_C0010202 NOPARALLEL;
ALTER INDEX DGPOS.SYS_C0010202 LOGGING;


ALTER INDEX DGPOS.SYS_C0010202 REBUILD ONLINE PARALLEL 4;	
ALTER INDEX DGPOS.SYS_C0010202 NOPARALLEL;
