GRANT CONNECT, CREATE SESSION to OMC;
GRANT CREATE PROCEDURE to OMC; 
GRANT UNLIMITED TABLESPACE to OMC; 
GRANT SELECT ANY DICTIONARY to OMC; 
GRANT CREATE TABLE to OMC; 
GRANT OEM_MONITOR to OMC; 
GRANT EXECUTE on SYS.DBMS_SERVER_ALERT to OMC; 
GRANT EXECUTE on SYS.DBMS_MANAGEMENT_PACKS to OMC; 
GRANT SELECT on APPQOSSYS.WLM_CLASSIFIER_PLAN to OMC; 
GRANT SELECT on APPQOSSYS.WLM_METRICS_STREAM to OMC; 
GRANT SELECT on APPQOSSYS.WLM_MPA_STREAM to OMC; 
GRANT SELECT on APPQOSSYS.WLM_VIOLATION_STREAM to OMC; 
GRANT EXECUTE on SYSMAN.MGMT_EMREP_OOB_MONITORING to OMC;

ALTER USER OMC QUOTA UNLIMITED ON DATAL03; (beri akses omc UNLIMITED ke tbs DATAL03)

GRANT CONNECT, CREATE SESSION to OMC;
GRANT CREATE PROCEDURE to OMC; 
GRANT SELECT ANY DICTIONARY to OMC; 
GRANT CREATE TABLE to OMC; 
GRANT OEM_MONITOR to OMC; 
GRANT EXECUTE on SYS.DBMS_SERVER_ALERT to OMC; 
GRANT EXECUTE on SYS.DBMS_MANAGEMENT_PACKS to OMC; 
GRANT SELECT on APPQOSSYS.WLM_CLASSIFIER_PLAN to OMC; 
GRANT SELECT on APPQOSSYS.WLM_METRICS_STREAM to OMC; 
GRANT SELECT on APPQOSSYS.WLM_MPA_STREAM to OMC; 
GRANT SELECT on APPQOSSYS.WLM_VIOLATION_STREAM to OMC; 
GRANT EXECUTE on SYSMAN.MGMT_EMREP_OOB_MONITORING to OMC;

ALTER USER YANA QUOTA UNLIMITED ON USERS; (beri akses YANA UNLIMITED ke tbs USERS)

GRANT SELECT on ftpaudit.record_set_stat to FTPOPS;

 SELECT * FROM DBA_ROLE_PRIVS WHERE GRANTEE = 'ARIS_SUPARDIMAN_X';
 ----cek grant------------------
COL GRANTEE FOR A30
COL OWNER FOR A30
COL TABLE_NAME FOR A30
COL GRANTOR FOR A30
COL PRIVILEGE FOR A30
COL GRANTABLE FOR A30
SET LINESIZE 300
SELECT * FROM DBA_TAB_PRIVS WHERE GRANTEE = 'ARIS_SUPARDIMAN_X';
 
 SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'ARIS_SUPARDIMAN_X';
 
 -----------------ATAU BISA MENGGUNAKAN----------------
 @user_ddl
 
lalu masukan nama usernya
 
 GRANT SELECT ON PRNO.T_GETIMSIHLR_LOG TO YUDOMO_HASTO_X on OPPRN
GRANT SELECT ON ITCRREPORT.DM_DLSPACK_MLY TO TDIRECT on OPTOIPIMC